version: '2'
services:
  openfoodfacts_db:
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: openfoodfacts
      MYSQL_USER: user
      MYSQL_PASSWORD: userpw